/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domen.KontaktOsoba;
import domen.Kupac;
import domen.Proizvod;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import logic.Kontroler;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;
import view.model.TableModelKontaktOsobe;
import view.model.TableModelKupci;
import view.model.TableModelProizvodi;

/**
 *
 * @author lvazi_000
 */
public class JFrameGlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLogin
     */
    public JFrameGlavnaForma() {
        initComponents();
        JDialogLogin login = new JDialogLogin(this, true);
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUnos = new javax.swing.JMenu();
        jMenuItemUnosKupca = new javax.swing.JMenuItem();
        jMenuItemUnosKontaktOsobe = new javax.swing.JMenuItem();
        jMenuItemUnosProdaje = new javax.swing.JMenuItem();
        jMenuItemUnosProizvoda = new javax.swing.JMenuItem();
        jMenuAzuriranje = new javax.swing.JMenu();
        jMenuItemAzuriranjeKupca = new javax.swing.JMenuItem();
        jMenuItemAzuriranjeKontaktOsobe = new javax.swing.JMenuItem();
        jMenuItemAzuriranjeProizvoda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuUnos.setText("Unos");

        jMenuItemUnosKupca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        jMenuItemUnosKupca.setText("Unos kupca");
        jMenuItemUnosKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosKupcaActionPerformed(evt);
            }
        });
        jMenuUnos.add(jMenuItemUnosKupca);

        jMenuItemUnosKontaktOsobe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        jMenuItemUnosKontaktOsobe.setText("Unos kontakt osobe");
        jMenuItemUnosKontaktOsobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosKontaktOsobeActionPerformed(evt);
            }
        });
        jMenuUnos.add(jMenuItemUnosKontaktOsobe);

        jMenuItemUnosProdaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMenuItemUnosProdaje.setText("Unos prodaje");
        jMenuItemUnosProdaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosProdajeActionPerformed(evt);
            }
        });
        jMenuUnos.add(jMenuItemUnosProdaje);

        jMenuItemUnosProizvoda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        jMenuItemUnosProizvoda.setText("Unos proizvoda");
        jMenuItemUnosProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosProizvodaActionPerformed(evt);
            }
        });
        jMenuUnos.add(jMenuItemUnosProizvoda);

        jMenuBar1.add(jMenuUnos);

        jMenuAzuriranje.setText("Ažuriranje");

        jMenuItemAzuriranjeKupca.setText("Ažuriranje kupca");
        jMenuItemAzuriranjeKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAzuriranjeKupcaActionPerformed(evt);
            }
        });
        jMenuAzuriranje.add(jMenuItemAzuriranjeKupca);

        jMenuItemAzuriranjeKontaktOsobe.setText("Ažuriranje kontakt osobe");
        jMenuItemAzuriranjeKontaktOsobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAzuriranjeKontaktOsobeActionPerformed(evt);
            }
        });
        jMenuAzuriranje.add(jMenuItemAzuriranjeKontaktOsobe);

        jMenuItemAzuriranjeProizvoda.setText("Ažuriranje proizvoda");
        jMenuItemAzuriranjeProizvoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAzuriranjeProizvodaActionPerformed(evt);
            }
        });
        jMenuAzuriranje.add(jMenuItemAzuriranjeProizvoda);

        jMenuBar1.add(jMenuAzuriranje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosKupcaActionPerformed

        JPanelUnosKupca panel = new JPanelUnosKupca();
        JDialog dialog = new JDialog(this, "Unos kupca", true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);


    }//GEN-LAST:event_jMenuItemUnosKupcaActionPerformed

    private void jMenuItemUnosKontaktOsobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosKontaktOsobeActionPerformed
        JPanelUnosKontaktOsobe panel = new JPanelUnosKontaktOsobe();
        JDialog dialog = new JDialog(this, "Unos kontakt osobe", true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosKontaktOsobeActionPerformed

    private void jMenuItemUnosProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosProizvodaActionPerformed

        JPanelUnosProizvoda panel = new JPanelUnosProizvoda();
        JDialog dialog = new JDialog(this, "Unos kontakt osobe", true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosProizvodaActionPerformed

    private void jMenuItemAzuriranjeKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAzuriranjeKupcaActionPerformed

        try {
            TableModelKupci model = new TableModelKupci(Kontroler.getInstance().vratiKupce());
            JPanelAzuriranje panel = new JPanelAzuriranje(model, "Naziv, PIB, MIB");
            JDialog dialog = new JDialog(this, "Ažuriranje kupaca", true);
            dialog.add(panel);
            dialog.pack();
            dialog.setVisible(true);
        } catch (Exception ex) {

            Logger.getLogger(JFrameGlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Nije moguće učitati listu kupaca", "Greška", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jMenuItemAzuriranjeKupcaActionPerformed

    private void jMenuItemAzuriranjeKontaktOsobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAzuriranjeKontaktOsobeActionPerformed

        try {
            TableModelKontaktOsobe model = new TableModelKontaktOsobe(Kontroler.getInstance().vratiKontaktOsobe());
            JPanelAzuriranje panel = new JPanelAzuriranje(model, "Ime, prezime, email, kupac");
            JDialog dialog = new JDialog(this, "Ažuriranje kontakt osoba", true);
            dialog.add(panel);
            dialog.pack();
            dialog.setVisible(true);
        } catch (Exception ex) {

            Logger.getLogger(JFrameGlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Nije moguće učitati listu kontakt osoba", "Greška", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jMenuItemAzuriranjeKontaktOsobeActionPerformed

    private void jMenuItemAzuriranjeProizvodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAzuriranjeProizvodaActionPerformed

        TableModelProizvodi model;
        try {
            model = new TableModelProizvodi(Kontroler.getInstance().vratiProizvode());
            JPanelAzuriranje panel = new JPanelAzuriranje(model, "Naziv, cena manja od");
            JDialog dialog = new JDialog(this, "Ažuriranje proizvoda", true);
            dialog.add(panel);
            dialog.pack();
            dialog.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFrameGlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Nije moguće učitati listu proizvoda", "Greška", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jMenuItemAzuriranjeProizvodaActionPerformed

    private void jMenuItemUnosProdajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosProdajeActionPerformed

        JPanelUnosProdaje panel = new JPanelUnosProdaje();
        JDialog dialog = new JDialog(this, "Unos prodaje", true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);


    }//GEN-LAST:event_jMenuItemUnosProdajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAzuriranje;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAzuriranjeKontaktOsobe;
    private javax.swing.JMenuItem jMenuItemAzuriranjeKupca;
    private javax.swing.JMenuItem jMenuItemAzuriranjeProizvoda;
    private javax.swing.JMenuItem jMenuItemUnosKontaktOsobe;
    private javax.swing.JMenuItem jMenuItemUnosKupca;
    private javax.swing.JMenuItem jMenuItemUnosProdaje;
    private javax.swing.JMenuItem jMenuItemUnosProizvoda;
    private javax.swing.JMenu jMenuUnos;
    // End of variables declaration//GEN-END:variables
}
