/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domen.KontaktOsoba;
import domen.Kupac;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import logic.Kontroler;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;

/**
 *
 * @author lvazi_000
 */
public class JPanelUnosKontaktOsobe extends javax.swing.JPanel {

    KontaktOsoba ko;

    private boolean izmena = false;

    /**
     * Creates new form JPanelUnosKontaktOsobe
     */
    public JPanelUnosKontaktOsobe() {
        initComponents();
        pripremiFormu();
        napraviOsobu();
    }

    public JPanelUnosKontaktOsobe(KontaktOsoba ko) {
        initComponents();
        try {
            this.ko = Kontroler.getInstance().ucitajOsobu(ko);
            pripremiFormu();

            jTextFieldIme.setText(ko.getIme());
            jTextFieldPrezime.setText(ko.getPrezime());
            jTextFieldTelefon.setText(ko.getTelefon());
            jTextFieldEmail.setText(ko.getEmail());
            jTextAreaNapomene.setText(ko.getNapomene());
            jComboBoxKupac.setSelectedItem(ko.getKupac());
            izmena = true;
            jButtonDodajKontaktOsobu.setText("Izmeni kontakt osobu");
            JOptionPane.showMessageDialog(this, "Sistem je prikazao podatke o kontakt osobi", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe izabranu kontakt osobu", "Greška", JOptionPane.ERROR_MESSAGE);
            this.getTopLevelAncestor().setVisible(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelKupac = new javax.swing.JLabel();
        jLabelIme = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabelPrezime = new javax.swing.JLabel();
        jTextFieldTelefon = new javax.swing.JTextField();
        jLabelTelefon = new javax.swing.JLabel();
        jComboBoxKupac = new javax.swing.JComboBox();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNapomene = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonDodajKontaktOsobu = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelKupac.setText("Kupac:");

        jLabelIme.setText("Ime:");

        jLabelPrezime.setText("Prezime:");

        jLabelTelefon.setText("Telefon:");

        jComboBoxKupac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelEmail.setText("Email:");

        jTextAreaNapomene.setColumns(20);
        jTextAreaNapomene.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNapomene);

        jLabel1.setText("Napomene:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIme)
                    .addComponent(jLabelKupac)
                    .addComponent(jLabelPrezime)
                    .addComponent(jLabelTelefon)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxKupac, 0, 252, Short.MAX_VALUE)
                    .addComponent(jTextFieldTelefon)
                    .addComponent(jTextFieldPrezime)
                    .addComponent(jTextFieldIme)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKupac)
                    .addComponent(jComboBoxKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIme)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrezime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonDodajKontaktOsobu.setText("Dodaj kontakt osobu");
        jButtonDodajKontaktOsobu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajKontaktOsobuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonDodajKontaktOsobu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDodajKontaktOsobu)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajKontaktOsobuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajKontaktOsobuActionPerformed

        try {

            ko.setIme(jTextFieldIme.getText());
            ko.setPrezime(jTextFieldPrezime.getText());
            ko.setTelefon(jTextFieldTelefon.getText());
            ko.setEmail(jTextFieldEmail.getText());
            ko.setNapomene(jTextAreaNapomene.getText());
            ko.setKupac((Kupac) jComboBoxKupac.getSelectedItem());
            ko.setKupid(ko.getKupac().getKupid());
            validacija.OsobaValidator.validiraj(ko);

            try {

                if (izmena) {
                    Kontroler.getInstance().azurirajKontaktOsobu(ko);
                } else {
                    Kontroler.getInstance().sacuvajKontaktOsobu(ko);
                }
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio kontakt osobu", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti kontakt osobu", "Greška", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(JPanelUnosKontaktOsobe.class.getName()).log(Level.SEVERE, null, exception);
                exception.printStackTrace();
            }

        } catch (Exception ex) {
            Logger.getLogger(JPanelUnosKontaktOsobe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButtonDodajKontaktOsobuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajKontaktOsobu;
    private javax.swing.JComboBox jComboBoxKupac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelKupac;
    private javax.swing.JLabel jLabelPrezime;
    private javax.swing.JLabel jLabelTelefon;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNapomene;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {

        try {
            jComboBoxKupac.setModel(new DefaultComboBoxModel(Kontroler.getInstance().vratiKupce().toArray()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Nije moguće učitati listu kupaca!", "Greška", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(JPanelUnosKontaktOsobe.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void napraviOsobu() {
        try {
            ko = Kontroler.getInstance().napraviOsobu();
            JOptionPane.showMessageDialog(this, "Sistem je napravio novu kontakt osobu", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da kreira novu kontakt osobu", "Greška", JOptionPane.ERROR_MESSAGE);

        }
    }
}
