/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domen.Proizvod;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logic.Kontroler;
import transfer.KlijentTransferObjekat;
import transfer.ServerTransferObjekat;
import view.model.TableModelProizvodi;

/**
 *
 * @author lvazi_000
 */
public class JPanelUnosProizvoda extends javax.swing.JPanel {

    TableModelProizvodi model;

    /**
     * Creates new form JPanelUnosProizvoda
     */
    public JPanelUnosProizvoda() {
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProizvodi = new javax.swing.JTable();
        jButtonSacuvajProizvode = new javax.swing.JButton();
        jButtonObrisiUnos = new javax.swing.JButton();
        jButtonDodajUnos = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTableProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableProizvodi);

        jButtonSacuvajProizvode.setText("Sačuvaj proizvode");
        jButtonSacuvajProizvode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajProizvodeActionPerformed(evt);
            }
        });

        jButtonObrisiUnos.setText("Obriši proizvod");
        jButtonObrisiUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiUnosActionPerformed(evt);
            }
        });

        jButtonDodajUnos.setText("Kreiraj novi proizvod");
        jButtonDodajUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajUnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSacuvajProizvode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisiUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDodajUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSacuvajProizvode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDodajUnos)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonObrisiUnos)))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajUnosActionPerformed

        try {
            Proizvod p = Kontroler.getInstance().napraviProizvod();
            JOptionPane.showMessageDialog(this, "Sistem je napravio novi proizvod", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            
            model.lista.add(p);
            model.fireTableDataChanged();
            

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Sistem ne može da kreira novi proizvod", "Greška", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButtonDodajUnosActionPerformed

    private void jButtonObrisiUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiUnosActionPerformed
        int i = jTableProizvodi.getSelectedRow();

        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Niste izbrali proizvod", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            model.lista.remove(i);
            model.fireTableDataChanged();
        }
    }//GEN-LAST:event_jButtonObrisiUnosActionPerformed

    private void jButtonSacuvajProizvodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajProizvodeActionPerformed

        try {
            Kontroler.getInstance().sacuvajProizvode(model.lista);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio proizvode", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            model.lista = new ArrayList<>();
            model.fireTableDataChanged();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti nove proizvode", "Greška", JOptionPane.ERROR_MESSAGE);

            Logger.getLogger(JPanelUnosProizvoda.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonSacuvajProizvodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajUnos;
    private javax.swing.JButton jButtonObrisiUnos;
    private javax.swing.JButton jButtonSacuvajProizvode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableProizvodi;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {

        model = new TableModelProizvodi();
        jTableProizvodi.setModel(model);

    }
}
